"""

Revision ID: 22889c494d05
Revises: bbe74b08f24f
Create Date: 2023-10-21 16:14:02.728189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22889c494d05'
down_revision = 'bbe74b08f24f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    gradeusertype_enum = postgresql.ENUM('intern', 'practice', name='gradeusertype', create_type=False)
    gradeusertype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('grade_requests', sa.Column('specialization_id', sa.Integer(), nullable=True))
    op.add_column('grade_requests', sa.Column('type', sa.Enum('intern', 'practice', name='gradeusertype'), nullable=True))
    op.create_foreign_key(None, 'grade_requests', 'specializations', ['specialization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grade_requests', type_='foreignkey')
    op.drop_column('grade_requests', 'type')
    op.drop_column('grade_requests', 'specialization_id')
    op.drop_table('specializations')
    # ### end Alembic commands ###
