"""

Revision ID: 235a395869ad
Revises: 22889c494d05
Create Date: 2023-10-21 22:27:44.234731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '235a395869ad'
down_revision = '22889c494d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    userroletype_enum = postgresql.ENUM('candidate', 'tech_lead', 'hr', name='userroletype', create_type=False)
    userroletype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade_requests', sa.Column('hr_id', sa.Integer(), nullable=True))
    op.add_column('grade_requests', sa.Column('tech_lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grade_requests', 'users', ['tech_lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'grade_requests', 'users', ['hr_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('source', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('candidate', 'tech_lead', 'hr', name='userroletype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'source')
    op.drop_constraint(None, 'grade_requests', type_='foreignkey')
    op.drop_constraint(None, 'grade_requests', type_='foreignkey')
    op.drop_column('grade_requests', 'tech_lead_id')
    op.drop_column('grade_requests', 'hr_id')
    # ### end Alembic commands ###
