"""

Revision ID: 2ad6b1d1c804
Revises: 1d5ad006781f
Create Date: 2023-10-20 22:45:25.009061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad6b1d1c804'
down_revision = '1d5ad006781f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('codes_question_id_fkey', 'codes', type_='foreignkey')
    op.create_foreign_key(None, 'codes', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_cases_code_id_fkey', 'test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'test_cases', 'codes', ['code_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('texts_question_id_fkey', 'texts', type_='foreignkey')
    op.create_foreign_key(None, 'texts', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.create_foreign_key('texts_question_id_fkey', 'texts', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.create_foreign_key('test_cases_code_id_fkey', 'test_cases', 'codes', ['code_id'], ['id'])
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.create_foreign_key('codes_question_id_fkey', 'codes', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
