"""

Revision ID: 7942750cd812
Revises: da02dd932b0e
Create Date: 2023-10-22 00:23:23.335463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7942750cd812'
down_revision = 'da02dd932b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('language', sa.String(), nullable=True))
    op.drop_column('answers', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('type', postgresql.ENUM('text', 'code', name='answertype'), autoincrement=False, nullable=False))
    op.drop_column('answers', 'language')
    # ### end Alembic commands ###
