"""

Revision ID: bbe74b08f24f
Revises: 41f0fba362bf
Create Date: 2023-10-21 13:20:56.791353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe74b08f24f'
down_revision = '41f0fba362bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_requests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('entering', 'tested', 'completed', 'department_interview', 'tech_lead_interview', name='graderequesttype'), nullable=True),
    sa.Column('resume', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_request_tests',
    sa.Column('grade_request_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_request_id'], ['grade_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('grade_request_id', sa.Integer(), nullable=True))
    op.drop_constraint('answers_user_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'grade_requests', ['grade_request_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_user_id_fkey', 'answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'grade_request_id')
    op.drop_table('grade_request_tests')
    op.drop_table('grade_requests')
    # ### end Alembic commands ###
