"""

Revision ID: cea600476d0b
Revises: 76a0dbbee9cf
Create Date: 2023-10-21 02:24:16.590593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea600476d0b'
down_revision = '76a0dbbee9cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_questions_test_id_fkey', 'test_questions', type_='foreignkey')
    op.drop_constraint('test_questions_question_id_fkey', 'test_questions', type_='foreignkey')
    op.create_foreign_key(None, 'test_questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_questions', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.create_foreign_key('test_questions_question_id_fkey', 'test_questions', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('test_questions_test_id_fkey', 'test_questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###
