"""

Revision ID: d7c669f826da
Revises: 2ad6b1d1c804
Create Date: 2023-10-21 01:32:24.810768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7c669f826da'
down_revision = '2ad6b1d1c804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('type', postgresql.ENUM('text', 'code', name='questiontype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
