"""

Revision ID: da02dd932b0e
Revises: e6acf51d8749
Create Date: 2023-10-22 00:04:54.720781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da02dd932b0e'
down_revision = 'e6acf51d8749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'content')
    # ### end Alembic commands ###
