name: Pre-commit&Test runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pip install poetry
        poetry install
        pip install pytest
    - name: Analysing the code with pre-commit and run tests
      run: |
        pre-commit install
        pre-commit run
        pytest tests
